# Generated by Django 2.2.1 on 2019-07-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='ammount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
