# Generated by Django 2.2.1 on 2019-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20190811_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='certificate',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='comp_package',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='declaration',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='sh_life',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='standard',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
